# Generated by Django 4.2.3 on 2023-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.TextField(verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(upload_to='blog/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='заголовок'),
        ),
    ]
