# Generated by Django 4.2.3 on 2023-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_vers',
            field=models.IntegerField(unique=True, verbose_name='номер версии'),
        ),
    ]
