# Generated by Django 4.2.3 on 2023-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_version_number_vers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='last_vers',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
