# Generated by Django 4.2.3 on 2023-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_version_last_vers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_vers',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
    ]
